CREATE TABLE person (
id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
name VARCHAR(50) NOT NULL,
date_of_birth DATE NOT NULL,
email VARCHAR(50) NOT NULL UNIQUE,
address VARCHAR(100)
);


CREATE TABLE book (
id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
label VARCHAR(50) NOT NULL,
author VARCHAR(50) NOT NULL,
release_date DATE NOT NULL,
assign_date DATE,
person_id INT REFERENCES person(id) ON DELETE SET NULL
);

INSERT INTO person(name, date_of_birth, email, address) VALUES('Dmitry Popov', '1999-07-09', 'rebeelsc@gmail.com', 'Russia, Barnaul, 656065');
INSERT INTO person(name, date_of_birth, email, address) VALUES('Polina Popova', '2000-02-25', 'polina@gmail.com', 'Russia, Barnaul, 656066');
INSERT INTO book(label, author, release_date) VALUES('Java', 'Bruce Ekkel', '2011-02-24');
INSERT INTO book(label, author, release_date) VALUES('SQL', 'SQL author', '2012-05-11');
